# Conversion of the matlab file
Here is the launching part for the conversion

In [5]:
from conversion import conversion_matlab_csv
data = conversion_matlab_csv.load_conversion('DATATESTRAW.mat')
data

        index  nb_seance  nb_passage  ...   x_force   y_force    z_force
0           0        0.0         0.0  ...  1.057183 -8.941128  31.378262
1           1        0.0         0.0  ...  1.183851 -8.263459  32.026108
2           2        0.0         0.0  ...  1.308062 -7.649749  32.628689
3           3        0.0         0.0  ...  1.429992 -7.098335  33.187741
4           4        0.0         0.0  ...  1.549815 -6.607554  33.704999
...       ...        ...         ...  ...       ...       ...        ...
499995   4995        9.0         9.0  ...  1.760153  9.349373  29.099964
499996   4996        9.0         9.0  ...  1.784167  9.327843  28.656276
499997   4997        9.0         9.0  ...  1.807832  9.308552  28.183878
499998   4998        9.0         9.0  ...  1.831152  9.291537  27.681607
499999   4999        9.0         9.0  ...  1.854130  9.276836  27.148298

[500000 rows x 12 columns]